url: https://y7kim.github.io #https://shanwiich.github.io #https://uhcougarettes.com/ #https://y7kim.github.io
baseurl: #/uhcougarettes #/agency-jekyll-theme/

# Site settings
title: Cougarettes
email: your-email@domain.com
description: "Welcome to UH Cougarettes! Our organization strives to build a sense of camaraderie amongst women in STEM."


# Team names, titles and social links
people:
- name: Shannon Lombardo
  pic: 1
  position: President
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/svlombardo
   # - title: twitter
   #   url: #
   # - title: facebook
   #   url: #
   # - title: stack-overflow
   #   url: #

#- name: Natalie Severino
#  pic: 2
#  position: Vice President
 # social:
   # - title: twitter
   #   url: #
   # - title: facebook
   #   url: #
   # - title: linkedin
   #   url: #

#- name: Mary Nguyen
#  pic: 3
#  position: Treasurer
#  social:
  #  - title: twitter
  #    url: #
  #  - title: facebook
  #    url: #
  #  - title: google-plus
   #   url: #
     
- name: Sana Akbani
  pic: 4
  position: Secretaryand Coding Event Coordinator
  social:
   # - title: facebook
  #    url: #
  #  - title: stack-overflow
   #   url: #
      
- name: Sara Umer
  pic: 5
  position: Marketing Chair
  social:
  #  - title: facebook
   #   url: #
   # - title: stack-overflow
   #   url: #
      
- name: Saarah Latiff
  pic: 6
  position: Eventing Coordinator
  social:
   # - title: twitter
   #   url: #
   # - title: facebook
   #   url: #
  #  - title: stack-overflow
   #   url: #
      
- name: Fatima Mirza
  pic: 7
  position: Recruitment Chair
  social:
 #   - title: twitter
 #     url: #
 #   - title: facebook
 #     url: #
 #   - title: stack-overflow
 #     url: #

- name: Jaelyn Rogers
  pic: 8
  position: Webmaster
  social:
 #   - title: twitter
 #     url: #
 #   - title: facebook
 #     url: #
 #   - title: stack-overflow
 #     url: #
 
 
- name: Tofi Oladipo
  pic: 9
  position: Communications Chair
  social:
 #   - title: twitter
 #     url: #
 #   - title: facebook
 #     url: #
 #   - title: stack-overflow
 #     url: #
 
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/uhcougarettes/?igshid=qge4kwdiiptk
  - title: gamepad
    url: https://discord.com/invite/cFRjD3B
  - title: comments
    url: https://groupme.com/join_group/60979871/n1IBXSg9
 # - title: bitbucket 
  #  url: http://bitbucket.org/jekyll
#  - title: github
  #  url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

theme: jekyll-theme-hacker
