url: https://y7kim.github.io #https://shanwiich.github.io #https://uhcougarettes.com/ #https://y7kim.github.io
baseurl: /uhcougarettes #/agency-jekyll-theme/

# Site settings
title: Cougarettes
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Maryum Mateen
  pic: 1
  position: President
  social:
   # - title: twitter
   #   url: #
   # - title: facebook
   #   url: #
   # - title: stack-overflow
   #   url: #

- name: Lena Luc
  pic: 2
  position: Vice President
  social:
   # - title: twitter
   #   url: #
   # - title: facebook
   #   url: #
   # - title: linkedin
   #   url: #

- name: Melika Nassizadeh
  pic: 3
  position: Event Coordinator
  social:
  #  - title: twitter
  #    url: #
  #  - title: facebook
  #    url: #
  #  - title: google-plus
   #   url: #
     
- name: Shannon Lombardo
  pic: 4
  position: Treasurer
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/svlombardo
   # - title: facebook
  #    url: #
  #  - title: stack-overflow
   #   url: #
      
- name: Mayssam Kalajo
  pic: 5
  position: Secretary
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/mayssam-kalajo-9289a0214/
  #  - title: facebook
   #   url: #
   # - title: stack-overflow
   #   url: #
      
- name: Iliana Chevez
  pic: 6
  position: Membership Chair
  social:
   # - title: twitter
   #   url: #
   # - title: facebook
   #   url: #
  #  - title: stack-overflow
   #   url: #
      
- name: Shannon Puliyampallil
  pic: 7
  position: Webmaster
  social:
 #   - title: twitter
 #     url: #
 #   - title: facebook
 #     url: #
 #   - title: stack-overflow
 #     url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/uhcougarettes/?igshid=qge4kwdiiptk
  - title: gamepad
    url: https://discord.com/invite/cFRjD3B
  #- title: stack-overflow
    #url: http://stackoverflow.com/questions/tagged/jekyll
 # - title: bitbucket 
  #  url: http://bitbucket.org/jekyll
#  - title: github
  #  url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
